# Generated by Django 6.0.6 on 2026-07-03 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['date']},
        ),
        migrations.AlterField(
            model_name='event',
            name='address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='event',
            name='capacity',
            field=models.PositiveIntegerField(),
        ),
    ]
