# Generated by Django 6.0.6 on 2026-07-07 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_options_alter_event_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='descr',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='address',
            new_name='location',
        ),
        migrations.RemoveField(
            model_name='event',
            name='capacity',
        ),
    ]
