# Generated by Django 6.0.6 on 2026-06-29 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='ruolo',
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('A', 'Attendee'), ('O', 'Organizer')], default='A', max_length=1),
        ),
    ]
